### ISSUE TITLE
Error when running npm run build (related to fibers install)

### ISSUE THREAD

**Issue by joeywas** [Azimuth1/SARCAT#7]
Following readme.md, after npm install (no errors), running npm run build results in an error in the fibers section.   Relevant output is in this gist:  https://gist.github.com/joeywas/14f289728696a51be0e81b03adab7baa

Snippet of output from above gist:

1649 error node v6.5.0
1650 error npm  v3.10.6
1651 error code ELIFECYCLE
1652 error fibers@1.0.5 install: `node ./build.js`
1652 error Exit status 1
1653 error Failed at the fibers@1.0.5 install script 'node ./build.js'.

**Comment by joeywas** [comment]
Not quite sure, but I believe this is related to an issue with meteor and node compatibility.  Ref:  https://github.com/meteor/meteor/issues/5124  

I got npm run build to work by using [nave](https://gist.github.com/isaacs/579814) prior to doing npm run build:

```
nave use 0.10.36
# to install npm in that virtualenv
curl https://www.npmjs.org/install.sh | sh
cd ~/SARCAT
npm run build
```

However when trying to npm start, I got this:

```
> sarcat@0.5.0 start /home/joseph/SARCAT
> node dist/app/index.js

begin
Using  existing sarcatStorage directory: /home/joseph/sarcatData
!!!!7266!!!!
PID: 7266 is not running
1
0 running mongod processes
!!!!7277!!!!
PID: 7277 is not running
1
0 running node processes
ready to start the database!!
Connecting to existing sarcatDB: /home/joseph/sarcatData/sarcatdb
mongod.lock size: 0
mongo port 27017 is not available. Trying port 27018

starting mongo

14903
ready to start sarcat!!
/home/joseph/SARCAT/dist/app/bundle/main.js
stderr: 

stderr: module.js:340
    throw err;
          ^

stderr: Error: Cannot find module '/home/joseph/SARCAT/dist/app/bundle/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "node" "/home/joseph/.nave/installed/0.10.36/bin/npm" "start"
npm ERR! node v0.10.36
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! sarcat@0.5.0 start: `node dist/app/index.js`
npm ERR! Exit status 8
```

**Comment by joeywas** [comment]
Gave up on trying to run the packaged version.   Moved on to attempt the Run Standalone guide.  Got it running with some minor tweaks.  Here are the commands I used to get SARCAT running in standalone:

```
nave use 0.10.36
# to install npm in that virtualenv
curl https://www.npmjs.org/install.sh | sh
cd ~/SARCAT
npm run build
# already had mongodb in home directory from previous attempt
mongod --dbpath ~/sarcatData/sarcatdb --port 27017
cd dist/app
export MONGO_URL=mongodb://localhost:27017/sarcatdb
export PORT=3000
export ROOT_URL=http://localhost/
export METEOR_SETTINGS=$(<settings.json)
# node bundle/main.js (failed, main.js doesn't exist there)
cd ~/SARCAT/dist/sarcat-0.5.0-os.linux.x86_64/app
# node bundle/main.js (failed, error from bcrypt about invalid elf header)
# http://stackoverflow.com/questions/29524874/invalid-elf-header-caused-by-bcrypt
cd bundle/programs/server/npm/npm-bcrypt/node_modules/
npm install bcrypt
cd ~/SARCAT/dist/sarcat-0.5.0-os.linux.x86_64/app
node bundle/main.js 
```
SARCAT is no running.  However I'm not comfortable trying to develop/contribute until I can become more familiar with node.js, meteor, and related modules.
